{"image": "https://mr-bricolage.bg/medias/sys_master/products/h53/hb0/8836726652958.jpg", "title": "АДАПТЕРИ ЗА ПОМПА 4 БР. FISHER", "price": {"total": "3,49", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "АДАПТЕРИ ЗА ПОМПА, 4 БР.FISHER"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h94/hd9/8809538093086.jpg", "title": "ЖИЛЕТКА СВЕТЛООТРЖ.ОРАНЖЕВА", "price": {"total": "5,29", "currency": "лв."}, "classifications": {"Произход": "КИТАЙ", "Наименование": "ЖИЛЕТКА СВЕТЛООТРЖ.ОРАНЖЕВА"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h94/h1f/8836734910494.jpg", "title": "ЗВЪНЕЦ ЗА КОЛЕЛО FISHER", "price": {"total": "2,49", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ЗВЪНЕЦ ЗА КОЛЕЛО FISHER"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h2b/h35/8836735369246.jpg", "title": "ЗВЪНЕЦ FISHER ЧЕРЕН АЛУМИНИЕВ", "price": {"total": "5,29", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ЧЕРЕН АЛУМИНИЕВ ЗВЪНЕЦ FISHER", "Материал": "АЛУМИНИЙ", "Цвят": "ЧЕРЕН"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h0c/h00/8836741333022.jpg", "title": "ЗАДЕН РЕФЛЕКТОР УНИВЕРСАЛЕН", "price": {"total": "3,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "УНИВЕРСАЛЕН ЗАДЕН РЕФЛЕКТОР"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hea/h09/8836735827998.jpg", "title": "ЗВЪНЕЦ КЛАСИЧЕСКИ FISHER ХРОМИРАН", "price": {"total": "3,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ХРОМИРАН КЛАСИЧЕСКИ ЗВЪНЕЦ FIS"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hee/h14/8863952666654.jpg", "title": "ЗАКАЧАЛКА ЗА ВЕЛОСИПЕД", "price": {"total": "5,99", "currency": "лв."}, "classifications": {"Наименование": "ЗАКАЧАЛКА ЗА ВЕЛОСИПЕД"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h16/h8e/8836746838046.jpg", "title": "ЗАКЛЮЧВАЩО УСТРОЙСТВО 120СМ 10ММ FISHER", "price": {"total": "15,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ЗАКЛЮЧ. УСТОЙСТВО 120 СМ, 10 М"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h61/h3d/8836746379294.jpg", "title": "ЗАКЛЮЧВАЩО УСТРОЙСТВО 100СМ 23ММ FISHER", "price": {"total": "19,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ЗАКЛЮЧ. УСТРОЙСТВО 100СМ, 23ММ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hd1/h46/8809537863710.jpg", "title": "ЖИЛЕТКА СВЕТЛООТРЖ.ЗЕЛЕНА", "price": {"total": "5,29", "currency": "лв."}, "classifications": {"Произход": "КИТАЙ", "Наименование": "ЖИЛЕТКА СВЕТЛООТРЖ.ЗЕЛЕНА"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h51/h18/8836737663006.jpg", "title": "ДЪРЖАЧ ЗА ШИШЕ FISHER АЛУМИНИЕВ", "price": {"total": "5,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "АЛУМИНИЕВ ДЪРЖАЧ ЗА ШИШЕ FISHE"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hb0/h40/8836749590558.jpg", "title": "ВЪТРЕШНА ГУМА 28X1.5-2.125 35 ММ FISHER", "price": {"total": "5,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ВЪТР. ГУМА 28X1.5-2.125, 35 ММ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h17/h14/8836741791774.jpg", "title": "ДЪРЖАЧ ЗА ПОМПИ FISHER УНИВЕРСАЛЕН", "price": {"total": "4,49", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "УНИВЕРСАЛЕН ДЪРЖАЧ ЗА ПОМПИ, F"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hfb/hc8/8836737204254.jpg", "title": "ДЕТСКО ШИШЕ ЗА ТЕЧНОСТИ 0.3Л FISHER", "price": {"total": "7,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ДЕТСКО ШИШЕ ЗА ТЕЧНОСТИ 0.3Л F"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h52/hda/8836749131806.jpg", "title": "ВЪТРЕШНА ГУМА 20X1.5-2.125 35 ММ FISHER", "price": {"total": "5,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ВЪТР. ГУМА 20X1.5-2.125, 35 ММ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h83/hcb/8836742250526.jpg", "title": "ДЕТСКА СЕДАЛКА ЗА ВЕЛОСИПЕД SELLEROYAL", "price": {"total": "27,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "SELLEROYAL ДЕТСКА СЕДАЛКА ЗА В"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/ha5/h86/8836730781726.jpg", "title": "ВЕНТИЛИ КОМПЛЕКТ FISHER DUNLOP", "price": {"total": "3,29", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "DUNLOP ВЕНТИЛИ FISHER"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h84/h7f/8836767285278.jpg", "title": "ВЪТРЕШНА ГУМА 26X1.5-2.125 35 ММ FISHER", "price": {"total": "5,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ВЪТР. ГУМА 26X1.5-2.125, 35 ММ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hcd/hd2/8836766826526.jpg", "title": "ВЪТРЕШНА ГУМА 24X1.5-2.125 40 ММ FISHER", "price": {"total": "5,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ВЪТР. ГУМА 24X1.5-2.125, 40 ММ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h57/h47/8857909461022.jpg", "title": "БАГАЖНИК ВЕЛОСИПЕД 2-3БР", "price": {"total": "59,99", "currency": "лв."}, "classifications": {"Допълнително описание": "БАГАЖНИК ВЕЛОСИПЕД 2 - 3 БРОЯ", "Марка": "AUTO PRACTIC", "Произход": "КИТАЙ", "Наименование": "БАГАЖНИК ВЕЛОСИПЕД 2 - 3 БРОЯ", "Модел": "2", "Цвят": "ЧЕРЕН"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hf6/hef/8857909231646.jpg", "title": "БАГАЖНИК ВЕЛОСИПЕД 1БР", "price": {"total": "44,99", "currency": "лв."}, "classifications": {"Допълнително описание": "БАГАЖНИК ВЕЛОСИПЕД 1 БРОЙ", "Марка": "AUTO PRACTIC", "Произход": "КИТАЙ", "Наименование": "БАГАЖНИК ВЕЛОСИПЕД 1 БРОЙ", "Цвят": "ЧЕРЕН"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h1b/h36/8836736745502.jpg", "title": "ОГЛЕДАЛО ЗА ОБРАТНО ВИЖДАНЕ,FISHER", "price": {"total": "3,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ОГЛЕДАЛО ЗА ОБРАТНО ВИЖДАНЕ,FI"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h43/h7a/8836731240478.jpg", "title": "КЛЮЧ ОТ ЗАКАЛЕНА СТОМАНА FISHER", "price": {"total": "5,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КЛЮЧ ОТ ЗАКАЛЕНА СТОМАНА FISHE"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hd8/h94/8836727570462.jpg", "title": "НАКЛАДКИ ЗА СПИРАЧКИ STANDARDFISHER", "price": {"total": "3,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "НАКЛАДКИ ЗА СПИРАЧКИ STANDARDF"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/ha5/h59/8813551878174.jpg", "title": "ТРОМБА", "price": {"total": "7,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ТРОМБА"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hef/h52/8836731699230.jpg", "title": "КЛЮЧ ЗА ЗАТЯГАНЕ НА СПИЦИ FISHER", "price": {"total": "3,79", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КЛЮЧ ЗА ЗАТЯГАНЕ НА СПИЦИ FISH"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h27/h4d/8836743626782.jpg", "title": "КОМПЮТЪР ЗА КОЛЕЛО TREND FISHER", "price": {"total": "21,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КОМПЮТЪР ЗА КОЛЕЛО \"TREND\" FIS"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h8f/hf3/8836734451742.jpg", "title": "ОБТЕГАЧ ЗА СЕДАЛКА FISHER АЛУМИНИЕВ", "price": {"total": "4,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "АЛУМИНИЕВ ОБТЕГАЧ ЗА СЕДАЛКА F"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/ha4/h9a/8836745920542.jpg", "title": "СПИРАЛ. ЗАКЛ. УСТРОЙСТВО 180 СМ FISHER", "price": {"total": "8,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "СПИРАЛ. ЗАКЛ. УСТРОЙСТВО 180 С"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h56/h26/8836739498014.jpg", "title": "КОШНИЦА ЗА КОЛЕЛО FISHER", "price": {"total": "13,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КОШНИЦА ЗА КОЛЕЛО FISHER"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h7b/hd2/8836728029214.jpg", "title": "НАКЛАДКИ КЕРАМИЧНИ V-BRAKE FISHER", "price": {"total": "5,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КЕРАМИЧНИ НАКЛАДКИ", "Модел": "V-BRAKE"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hed/hb0/8836738580510.jpg", "title": "СТОЙКА ЗА ВЕЛОСИПЕД 12-20 FISHER", "price": {"total": "9,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "СТОЙКА ЗА ВЕЛОСИПЕД 12-20 \"FIS"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h98/he9/8836742709278.jpg", "title": "ТРОМБА ХРОМИРАНА FISHER", "price": {"total": "6,69", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ТРОМБА, ХРОМИРАНА FISHER"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h7e/hbd/8836744085534.jpg", "title": "КОШНИЦА ЗА КОЛЕЛО 5 КГ", "price": {"total": "23,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КОШНИЦА ЗА КОЛЕЛО, 5 КГ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/hc8/h04/8836727111710.jpg", "title": "УНИВЕРСАЛНО ЖИЛО ЗА СПИРАЧКИ FISHER", "price": {"total": "3,59", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "УНИВЕРСАЛНО ЖИЛО ЗА СПИРАЧКИ,F"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h0e/h88/8836745003038.jpg", "title": "КАСКА ЗА КОЛЕЛО BLUE S/M 54-58", "price": {"total": "43,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КАСКА ЗА КОЛЕЛО \"BLUE\" S/M 54-"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h78/hb7/8836740874270.jpg", "title": "КАЛНИЦИ ЗА ВЕЛОСИПЕД 24-26 FISHER К-Т", "price": {"total": "15,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "К-Т КАЛНИЦИ ЗА ВЕЛОСИПЕД  24-2"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/ha9/ha8/8836747755550.jpg", "title": "МИНИ ПОМПА С ДВОЕН ХОД", "price": {"total": "11,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "МИНИ ПОМПА С ДВОЕН ХОД"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h89/h64/8842001776670.jpg", "title": "СТОП 5LED ЧЕРВЕНА ВЕЛО B03", "price": {"total": "9,99", "currency": "лв."}, "classifications": {"Марка": "DURACELL", "Гаранция": "2 \n\t\t\t\t\t\t\t\t\t\tyr", "Наименование": "СТОП 5LED"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h12/ha6/8836732157982.jpg", "title": "ЛЕПЕНКИ ЗА БЪРЗО ЗАЛЕПВАНЕ FISHER 6БР", "price": {"total": "5,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ЛЕПЕНКИ ЗА БЪРЗО ЗАЛЕПВАНЕ, 6"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h7a/h18/8842003152926.jpg", "title": "ФАР 3LED БЯЛА ВЕЛО F02", "price": {"total": "10,99", "currency": "лв."}, "classifications": {"Марка": "DURACELL", "Гаранция": "2 \n\t\t\t\t\t\t\t\t\t\tyr", "Произход": "КИТАЙ", "Наименование": "ФАР 3LED"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h86/h1b/8836740415518.jpg", "title": "РЪКОХВАТКИ ЗА КОЛЕЛО FISHER УНИВЕРСАЛНИ", "price": {"total": "7,49", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "УНИВЕРСАЛ. РЪКОХВАТКИ ЗА КОЛЕЛ"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h05/hd6/8842000400414.jpg", "title": "СТОП 3LED ЧЕРВЕНА ВЕЛО B02", "price": {"total": "10,99", "currency": "лв."}, "classifications": {"Марка": "DURACELL", "Гаранция": "2 \n\t\t\t\t\t\t\t\t\t\tyr", "Произход": "КИТАЙ", "Наименование": "СТОП 3LED ЧЕРВЕНА ВЕЛО"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h74/h6b/8836738121758.jpg", "title": "СТОЙКА ЗА ВЕЛОСИПЕД 20-28 FISHER АЛУМ.", "price": {"total": "9,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "АЛУМ. СТОЙКА ЗА ВЕЛОСИПЕД 20-2"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h10/h0e/8836743168030.jpg", "title": "ЗВЪНЕЦ ФУТБОЛ", "price": {"total": "4,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "ЗВЪНЕЦ \"ФУТБОЛ\""}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/he2/h99/8836745461790.jpg", "title": "КАСКА ЗА КОЛЕЛО BLUE L/XL 56-62", "price": {"total": "43,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КАСКА ЗА КОЛЕЛО \"BLUE L/XL 56-"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h6c/h65/8836739956766.jpg", "title": "КОШНИЦА ЗА КОЛЕЛО KIDS FISHER", "price": {"total": "9,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "КОШНИЦА ЗА КОЛЕЛО \"KIDS\" FISHE"}}
{"image": "https://mr-bricolage.bg/medias/sys_master/products/h2d/h8e/8836747296798.jpg", "title": "СПИРАЛ. ЗАКЛЮЧ. У-ВО 80СМ, 18ММ, FISHER", "price": {"total": "9,99", "currency": "лв."}, "classifications": {"Марка": "FISCHER", "Произход": "КИТАЙ", "Наименование": "СПИРАЛ. ЗАКЛЮЧ. У-ВО 80СМ, 18М"}}
